"use client";

import { Exo } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Navbar from "@/components/Navbar";
import { useEffect, useState } from "react";

const exo = Exo({ subsets: ["latin"], weight: ["400", "700"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isDarkMode, setIsDarkMode] = useState(true);

  useEffect(() => {
    const savedTheme = localStorage.getItem("theme");
    if (savedTheme) {
      setIsDarkMode(savedTheme === "dark");
    }
  }, []);

  useEffect(() => {
    localStorage.setItem("theme", isDarkMode ? "dark" : "light");
  }, [isDarkMode]);

  const toggleTheme = () => {
    setIsDarkMode(!isDarkMode);
  };

  return (
    <html lang="en" className={isDarkMode ? "dark" : ""}>
      <head>
        <link rel="icon" href="/favicon.ico" />
        <title>gorubari</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={exo.className}>
        <div
          className={`relative min-h-screen flex flex-col items-center justify-center p-4
            ${
              isDarkMode
                ? "bg-gradient-to-t from-[#000105] via-[#2c3e42] to-[#000b0f] text-white before:absolute before:inset-0 before:bg-[radial-gradient(circle,rgba(255,255,255,0.08)_0%,transparent_50%)] before:blur-2xl before:opacity-50"
                : "bg-gradient-to-t from-gray-300 to-gray-100 text-black"
            }`}
        >
          <Navbar toggleTheme={toggleTheme} isDarkMode={isDarkMode} />
          {children}
        </div>
      </body>
    </html>
  );
}
