import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const exo = Exo({ subsets: ["latin"], weight: ["400", "700"] });
import { Imprima } from "next/font/google";

// const roboto = Imprima({
//   weight: "400",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Clothings Bee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/public/favicon.ico" />{" "}
        {/* Add your favicon file here */}
        <title>Clothings Bee</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={exo.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
